[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wvcr"
version = "0.1.0"
authors = [
    {name = "Your Name"}
]
description = "Voice recording and transcription tool"
requires-python = ">=3.9"
dependencies = [
    "pyaudio",
    "loguru",
    "openai",
    "wave",
    "pyperclip",
]

[project.scripts]
wvcr = "wvcr.main:main"

[tool.hatch.build.targets.wheel]
packages = ["wvcr"]

[tool.hatch.build]
artifacts = [
    "data/",
]